### PR TITLE
Interfaces

### PR DESCRIPTION
**Pull request by hupebln**
# Add get_interfaces

## Description
I couldn't find an endpoint to get information about interfaces, but used the cli endpoint to get the output of the cli.

It will be parsed for interfaces and is doing another calls on all interfaces to get more specific information about the interfaces as we need this to fill the expected template by napalm.
Needed to implement the asynchronous call into the method as all other calls are synchronous and this would take much longer to process on all interfaces.
Maybe a good idea to implement only asynchronous calls instead of synchronous calls for all methods!?

I don't know right now if there could be another naming format for interfaces too. On the test device I could only see integers for the interfaces (I guess 1-10). Are there maybe also other formats like ge0/0/0???

### CODE REVIEW

**Comment by gcotone** [comment]
Yes, the `cli()` method is the only option. How fast was to get all the interface information on the 2530-8G?

On my tests, API calls turned out to be very expensive. Aruba switches showed to have some sort of CPU protection where they rate-limit API calls to 1 call/5sec, so it may take  `(num_interfaces * 5) + 5` seconds for `get_interfaces()` to return something.

I think we'd better off doing a single `cli("display interface")` and parsing it with textfsm as we did with `get_arp_table()` or `get_route_to()`. 

@hupebln  What do you think?

**Comment by hupebln** [comment]
@gcotone synchronous it was around 55 seconds and asynchronous around 25 when I timed it.

"display interface" is actually way better. I'll look into it to parse it.
But still the question if the name of the interfaces is always an integer. Have you seen another formats on these devices?

**Comment by gcotone** [comment]
It's not always an `int`. Interface name is platform dependant and also user-configurable (can be renamed), so potentially it could be any word `\w` including dashes, dots and slashes.

**Comment by hupebln** [comment]
I've rebuilt the method and use **display interface** + **show interfaces brief** asynchronously.
textfsm is used now as well, instead of manually regex'ing

But there are still values missing:
* last_flapped
* mtu

**Comment by gcotone** [comment]
@hupebln interface MTU is displayed as `The Maximum Frame Length`, e.g.:

```
switch# display interface 
 IP Packet Frame Type: n/a, Hardware Address: 3821c7-b93f0f
 Description: 1 interface
 Loopback is n/a
 Media type is twisted Pair
 Port hardware type is 100/1000T
 1000Mbps-speed mode,  full-duplex mode
 Link speed type is autonegotiation, link duplex type is autonegotiation
 Flow-control is not enabled
 The Maximum Frame Length is 9216
...
```

Additionally, if the interface is admin disabled, it can be extracted directly from `display interface`:
``` 
switch# display interface | beg Administratively
 8 current state: DOWN ( Administratively )
 IP Packet Frame Type: n/a, Hardware Address: 3821c7-b93f08
 Description: 8 interface
...
```
`last_flapped` seems to be not available

**Comment by hupebln** [comment]
I'll implement it like discussed, but will close it here and take care of the async beforehand.

**Pull request closed without merging**
